### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by raffaelemancuso** [Synthaze/bibtools#1]
DELETE

**Comment by Synthaze** [comment]
Thank for reporting, this is now fixed in `bibtools-pkg==0.1.16`.

`pip3 install bibtools-pkg --upgrade`

Also do not use quotes for PMIDs or DOIs. It works well with:

`bibtools -i 10.1002/chem.201902320`

For the dependencies exact versions are here just to make sure it will work as is.  But it will most likely work with latest versions too.

**Comment by raffaelemancuso** [comment]
DELETE

**Comment by Synthaze** [comment]
If the paper is not on PubMed as an open-access, then it is downloaded from sci-hub. Which is the case for `10.1002/chem.201902320`.

The metadata retrieved are always from PubMed/MedLine, however.

I close the issue since the initial problem seems to be resolved.
